// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace CustardRM
{
    public partial class ProfitabilityScoreModel
    {
        /// <summary>
        /// model input class for ProfitabilityScoreModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ProfitMargin")]
            public float ProfitMargin { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"SalesVelocity")]
            public float SalesVelocity { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"AvgReviewRating")]
            public float AvgReviewRating { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"DiscountRate")]
            public float DiscountRate { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"StockTurnoverRate")]
            public float StockTurnoverRate { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"HoldingCostEstimate")]
            public float HoldingCostEstimate { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"ProfitabilityScore")]
            public float ProfitabilityScore { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ProfitabilityScoreModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ProfitMargin")]
            public float ProfitMargin { get; set; }

            [ColumnName(@"SalesVelocity")]
            public float SalesVelocity { get; set; }

            [ColumnName(@"AvgReviewRating")]
            public float AvgReviewRating { get; set; }

            [ColumnName(@"DiscountRate")]
            public float DiscountRate { get; set; }

            [ColumnName(@"StockTurnoverRate")]
            public float StockTurnoverRate { get; set; }

            [ColumnName(@"HoldingCostEstimate")]
            public float HoldingCostEstimate { get; set; }

            [ColumnName(@"ProfitabilityScore")]
            public float ProfitabilityScore { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("AI/Models/ProfitabilityScoreModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
