// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace CustardRM
{
    public partial class SuggestedReorderQuantityModel
    {
        /// <summary>
        /// model input class for SuggestedReorderQuantityModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"AvgDailyConsumption")]
            public float AvgDailyConsumption { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"StockLevel")]
            public float StockLevel { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"AvgLeadTime")]
            public float AvgLeadTime { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"LeadTimeVariance")]
            public float LeadTimeVariance { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"DaysSinceLastOrder")]
            public float DaysSinceLastOrder { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"SuggestedReorderQuantity")]
            public float SuggestedReorderQuantity { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SuggestedReorderQuantityModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"AvgDailyConsumption")]
            public float AvgDailyConsumption { get; set; }

            [ColumnName(@"StockLevel")]
            public float StockLevel { get; set; }

            [ColumnName(@"AvgLeadTime")]
            public float AvgLeadTime { get; set; }

            [ColumnName(@"LeadTimeVariance")]
            public float LeadTimeVariance { get; set; }

            [ColumnName(@"DaysSinceLastOrder")]
            public float DaysSinceLastOrder { get; set; }

            [ColumnName(@"SuggestedReorderQuantity")]
            public float SuggestedReorderQuantity { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("AI/Models/SuggestedReorderQuantityModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
